version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - aws cloudformation package --template-file template.yaml --s3-bucket mng-mobile-notification-bucket --output-template-file template.yaml
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  type: zip
  files:
    - template.yaml