version: 0.2
env:
  variables:
    TEMPLATE_FILE: "template.yaml"
    OUTPUT_TEMPLATE_FILE: "packaged-template.yaml"
    S3_BUCKET: "mng-mobile-notification-system-bucket-001"
    STACK : "mng-mobile-notification-system"
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - pip install --upgrade awscli
  build:
    commands:
      - echo Build started on `date`
      - sam build
      - sam deploy --s3-bucket $S3_BUCKET --stack-name $STACK --capabilities CAPABILITY_IAM --no-confirm-changeset
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - $OUTPUT_TEMPLATE_FILE