version = 0.1
[DEV]
[DEV.deploy]
[DEV.deploy.parameters]
stack_name = "push-notification"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-iudvkytjtstr"
s3_prefix = "push-notification"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "push-notification"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-iudvkytjtstr"
s3_prefix = "push-notification"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
