version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mng-mobile-notification-system"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1li4q4wgc7fnm"
s3_prefix = "mng-mobile-notification-system"
region = "ap-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"Dev\""

