version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sns-notification"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1c09eaql2e70k"
s3_prefix = "sns-notification"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"Dev\""

[Dev]
[Dev.deploy]
[Dev.deploy.parameters]
stack_name = "sns-notification"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1c09eaql2e70k"
s3_prefix = "sns-notification"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"Dev\""

[y]
[y.deploy]
[y.deploy.parameters]
stack_name = "sns-notification"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1c09eaql2e70k"
s3_prefix = "sns-notification"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"Dev\""
