version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "push-sample-01"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-iudvkytjtstr"
s3_prefix = "push-sample-01"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
